### PR TITLE
Wrap ducc0 using jaxbin as optional contributed sub-package

### PR DESCRIPTION
**Pull request by Edenhofer**
This is mostly copying over code from the tests putting it into the main package. As the sub-package is not imported by default, it does not add an additional dependency.

@mreineck Can you help me sort out the SHT? I think we mostly just need a sensible defaults akin to NIFTy but I wasn't able to figure out all the necessary parameters.

### CODE REVIEW

**Comment by roth-jakob** [comment]
I have added a binding for the wgridder on #7.  I have not explicitly exposed all the arguments of the wgridder but just the ones we use in resolve. @mreineck, do you think the other arguments are frequently used, and we should explicitly expose them?

**Comment by roth-jakob** [comment]
I think ducc.fft.c2c and ducc.fft.genuine_fht natively support batching.  We could support native batching as in the demo_lin. @Edenhofer, if you are unsure about that, I could add it.

**Comment by Edenhofer** [comment]
Good point. Happy to add it on Monday or Tuesday but feel free to work on it right now if you have the time :)

**Comment by mreineck** [comment]
Concerning the SHT: I would not set any defaults (except for `nthreads=1`, as there are no "obvious" choices (at least, to different users different choices may be obvious...). It's not a huge number of parameters, so I think specifyig them all is not a real burden.

**Comment by mreineck** [comment]
I'm not totally sure about exposing `random_alm` : it should strictly be used for testing and is probably not too helpful for end users. So we could perhaps rename it to `_random_alm` and still use it in the tests, or directly move it to the test scripts.
`nalm` is probably generally useful: the only reason I don't have it in `ducc0` is that going to C++ for such a trivial function is probably overkill. If we want to make it public, should we rename it to `n_alm` or `number_of_alm`?

**Comment by mreineck** [comment]
Concerning `wgridder`: I think the currently exposed arguments are a very good starting point. If it becomes obvious that more parameters are needed, we can add them and set their default to what's currently already used by default, so the interface won't break.

**Comment by Edenhofer** [comment]
> I'm not totally sure about exposing `random_alm` : it should strictly be used for testing and is probably not too helpful for end users. So we could perhaps rename it to `_random_alm` and still use it in the tests, or directly move it to the test scripts.

Agreed. I moved it to tests.

> `nalm` is probably generally useful: the only reason I don't have it in `ducc0` is that going to C++ for such a trivial function is probably overkill. If we want to make it public, should we rename it to `n_alm` or `number_of_alm`?

I like the name `nalm`. It might be considered a bit cryptic but I believe that to be outweigh by convenience. In a way it is similar to `ndim` which is also not spelled out in numpy and the like.

**Comment by mreineck** [comment]
I'm still using `_alm2realalm` in the tests, which is private. This happens because our typical storage scheme for `a_lm` will not work in gradient tests for complicated reasons. The "real a_lm" format I'm using to work around this is not really wide-spread and I don't want to impose this as the format to use when doing SHTs with JAX; this is just meant to be an example. So if we can live with this test being a bit "informal", this PR should be done (except for formatting etc.)

**Comment by Edenhofer** [comment]
> I think ducc.fft.c2c and ducc.fft.genuine_fht natively support batching. We could support native batching as in the demo_lin.

Done. Can you double check the interaction between `batch_axes` and `axes`? It should be tested but I think another pair of eyes on it would be great.

**Comment by roth-jakob** [comment]
> > I think ducc.fft.c2c and ducc.fft.genuine_fht natively support batching. We could support native batching as in the demo_lin.
> 
> Done. Can you double check the interaction between `batch_axes` and `axes`? It should be tested but I think another pair of eyes on it would be great.

Thanks for adding that. Looks good to me.

**Review by mreineck — APPROVED** [review]

**Pull request merged**
