### PR TITLE
update arxiv tex file

### PR DESCRIPTION
**Pull request by roth-jakob**

### CODE REVIEW

**Comment by Edenhofer** [comment]
hmm, when I run
```sh
sudo docker run --rm \
    --volume $PWD:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/paperdraft -k paper.md
```
in the paper folder, I get a slightly different TeX file. I pushed the diff to `update_arxiv2`.

**Comment by roth-jakob** [comment]
I have no idea why you get something slightly different. I think I prefer my tex file as it links the citations in the text so that you can click on them and jump to the corresponding reference in the reference list. I haven't spotted any other significant difference.

If it's ok with you I would take my version.

**Comment by Edenhofer** [comment]
Sure, that's a big plus. Let's proceed with yours then.

Did you run a different command from the one I did?

**Comment by roth-jakob** [comment]
I used nearly the same command:

```
sudo docker run --rm \             
    --volume $PWD/paper:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/inara \

```
I manually replaced the header in the tex file with the header of the old tex file. Additionally, I manually replaced ` with normal ' in the text, as it was in the old tex file.

**Pull request merged**
